In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm


In [2]:
def find_rep_period(num1, num2):
    seq = [num1, num2]
    
    #using dictionary to check for repeats
    prevseen_patterns = {(num1, num2): 0}

    # using a for loop to prevent crash from inifinite loop
    for j in range(1, 1000):
        
        #calculating next term in sequence        
        next_num = (seq[-1]+seq[-2]) % 10
        seq.append(next_num)

        current_pattern = (seq[-2], seq[-1])
    
    
        #checking if the newly calculated values are a repeat of any previous ones
        if current_pattern in prevseen_patterns:
            return j

        prevseen_patterns[current_pattern] = j

    return None  # If no repetitions are found

periods=[]
count  = 0

per = np.empty((100,3))
for a in range(10):
    for b in range(10):
        result_period = find_rep_period(a,b)
        periods.append(result_period)
        per[count][0] = a
        per[count][1] = b
        per[count][2] = result_period
        count+=1
        
print(periods)
print(per)


[1, 60, 20, 60, 20, 3, 20, 60, 20, 60, 60, 60, 60, 12, 60, 60, 60, 60, 12, 60, 20, 12, 20, 60, 20, 60, 4, 60, 20, 60, 60, 60, 60, 60, 12, 60, 60, 60, 60, 12, 20, 60, 4, 60, 20, 60, 20, 12, 20, 60, 3, 60, 60, 60, 60, 3, 60, 60, 60, 60, 20, 60, 20, 12, 20, 60, 20, 60, 4, 60, 60, 12, 60, 60, 60, 60, 12, 60, 60, 60, 20, 60, 20, 60, 4, 60, 20, 60, 20, 12, 60, 60, 12, 60, 60, 60, 60, 12, 60, 60]
[[ 0.  0.  1.]
 [ 0.  1. 60.]
 [ 0.  2. 20.]
 [ 0.  3. 60.]
 [ 0.  4. 20.]
 [ 0.  5.  3.]
 [ 0.  6. 20.]
 [ 0.  7. 60.]
 [ 0.  8. 20.]
 [ 0.  9. 60.]
 [ 1.  0. 60.]
 [ 1.  1. 60.]
 [ 1.  2. 60.]
 [ 1.  3. 12.]
 [ 1.  4. 60.]
 [ 1.  5. 60.]
 [ 1.  6. 60.]
 [ 1.  7. 60.]
 [ 1.  8. 12.]
 [ 1.  9. 60.]
 [ 2.  0. 20.]
 [ 2.  1. 12.]
 [ 2.  2. 20.]
 [ 2.  3. 60.]
 [ 2.  4. 20.]
 [ 2.  5. 60.]
 [ 2.  6.  4.]
 [ 2.  7. 60.]
 [ 2.  8. 20.]
 [ 2.  9. 60.]
 [ 3.  0. 60.]
 [ 3.  1. 60.]
 [ 3.  2. 60.]
 [ 3.  3. 60.]
 [ 3.  4. 12.]
 [ 3.  5. 60.]
 [ 3.  6. 60.]
 [ 3.  7. 60.]
 [ 3.  8. 60.]
 [ 3.  9. 12.]
 [ 4.  